title: Css Advanced
email: desi011@abv.bg
description: Hello there!  
destination: docs
baseurl: ""
url: "" 
twitter_username: desitynik
github_username:  desitynikolova


plugins:
  - jekyll-feed


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
